create table CAL
(
    WEEK    VARCHAR2(1),
    DAY     VARCHAR2(4),
    NUM_DAY VARCHAR2(2)
)
/

INSERT INTO HR.CAL (WEEK, DAY, NUM_DAY) VALUES ('1', '일', '1');
INSERT INTO HR.CAL (WEEK, DAY, NUM_DAY) VALUES ('1', '월', '2');
INSERT INTO HR.CAL (WEEK, DAY, NUM_DAY) VALUES ('1', '화', '3');
INSERT INTO HR.CAL (WEEK, DAY, NUM_DAY) VALUES ('1', '수', '4');
INSERT INTO HR.CAL (WEEK, DAY, NUM_DAY) VALUES ('1', '목', '5');
INSERT INTO HR.CAL (WEEK, DAY, NUM_DAY) VALUES ('1', '금', '6');
INSERT INTO HR.CAL (WEEK, DAY, NUM_DAY) VALUES ('1', '토', '7');
INSERT INTO HR.CAL (WEEK, DAY, NUM_DAY) VALUES ('2', '일', '8');
INSERT INTO HR.CAL (WEEK, DAY, NUM_DAY) VALUES ('2', '월', '9');
INSERT INTO HR.CAL (WEEK, DAY, NUM_DAY) VALUES ('2', '화', '10');
INSERT INTO HR.CAL (WEEK, DAY, NUM_DAY) VALUES ('2', '수', '11');
INSERT INTO HR.CAL (WEEK, DAY, NUM_DAY) VALUES ('2', '목', '12');
INSERT INTO HR.CAL (WEEK, DAY, NUM_DAY) VALUES ('2', '금', '13');
INSERT INTO HR.CAL (WEEK, DAY, NUM_DAY) VALUES ('2', '토', '14');
INSERT INTO HR.CAL (WEEK, DAY, NUM_DAY) VALUES ('3', '일', '15');
INSERT INTO HR.CAL (WEEK, DAY, NUM_DAY) VALUES ('3', '월', '16');
INSERT INTO HR.CAL (WEEK, DAY, NUM_DAY) VALUES ('3', '화', '17');
INSERT INTO HR.CAL (WEEK, DAY, NUM_DAY) VALUES ('3', '수', '18');
INSERT INTO HR.CAL (WEEK, DAY, NUM_DAY) VALUES ('3', '목', '19');
INSERT INTO HR.CAL (WEEK, DAY, NUM_DAY) VALUES ('3', '금', '20');
INSERT INTO HR.CAL (WEEK, DAY, NUM_DAY) VALUES ('3', '토', '21');
INSERT INTO HR.CAL (WEEK, DAY, NUM_DAY) VALUES ('4', '일', '22');
INSERT INTO HR.CAL (WEEK, DAY, NUM_DAY) VALUES ('4', '월', '23');
INSERT INTO HR.CAL (WEEK, DAY, NUM_DAY) VALUES ('4', '화', '24');
INSERT INTO HR.CAL (WEEK, DAY, NUM_DAY) VALUES ('4', '수', '25');
INSERT INTO HR.CAL (WEEK, DAY, NUM_DAY) VALUES ('4', '목', '26');
INSERT INTO HR.CAL (WEEK, DAY, NUM_DAY) VALUES ('4', '금', '27');
INSERT INTO HR.CAL (WEEK, DAY, NUM_DAY) VALUES ('4', '토', '28');
INSERT INTO HR.CAL (WEEK, DAY, NUM_DAY) VALUES ('5', '일', '29');
INSERT INTO HR.CAL (WEEK, DAY, NUM_DAY) VALUES ('5', '월', '30');
INSERT INTO HR.CAL (WEEK, DAY, NUM_DAY) VALUES ('5', '화', '31');