create table COUNTRIES
(
    COUNTRY_ID   CHAR(2) not null
        constraint COUNTRY_C_ID_PK
            primary key
        constraint COUNTRY_ID_NN
            check ("COUNTRY_ID" IS NOT NULL),
    COUNTRY_NAME VARCHAR2(40),
    REGION_ID    NUMBER
        constraint COUNTR_REG_FK
            references REGIONS
)
    organization index
/

comment on table COUNTRIES is 'country table. Contains 25 rows. References with locations table.'
/

comment on column COUNTRIES.COUNTRY_ID is 'Primary key of countries table.'
/

comment on column COUNTRIES.COUNTRY_NAME is 'Country name'
/

comment on column COUNTRIES.REGION_ID is 'Region ID for the country. Foreign key to region_id column in the departments table.'
/

INSERT INTO HR.COUNTRIES (COUNTRY_ID, COUNTRY_NAME, REGION_ID) VALUES ('AR', 'Argentina', 2);
INSERT INTO HR.COUNTRIES (COUNTRY_ID, COUNTRY_NAME, REGION_ID) VALUES ('AU', 'Australia', 3);
INSERT INTO HR.COUNTRIES (COUNTRY_ID, COUNTRY_NAME, REGION_ID) VALUES ('BE', 'Belgium', 1);
INSERT INTO HR.COUNTRIES (COUNTRY_ID, COUNTRY_NAME, REGION_ID) VALUES ('BR', 'Brazil', 2);
INSERT INTO HR.COUNTRIES (COUNTRY_ID, COUNTRY_NAME, REGION_ID) VALUES ('CA', 'Canada', 2);
INSERT INTO HR.COUNTRIES (COUNTRY_ID, COUNTRY_NAME, REGION_ID) VALUES ('CH', 'Switzerland', 1);
INSERT INTO HR.COUNTRIES (COUNTRY_ID, COUNTRY_NAME, REGION_ID) VALUES ('CN', 'China', 3);
INSERT INTO HR.COUNTRIES (COUNTRY_ID, COUNTRY_NAME, REGION_ID) VALUES ('DE', 'Germany', 1);
INSERT INTO HR.COUNTRIES (COUNTRY_ID, COUNTRY_NAME, REGION_ID) VALUES ('DK', 'Denmark', 1);
INSERT INTO HR.COUNTRIES (COUNTRY_ID, COUNTRY_NAME, REGION_ID) VALUES ('EG', 'Egypt', 4);
INSERT INTO HR.COUNTRIES (COUNTRY_ID, COUNTRY_NAME, REGION_ID) VALUES ('FR', 'France', 1);
INSERT INTO HR.COUNTRIES (COUNTRY_ID, COUNTRY_NAME, REGION_ID) VALUES ('IL', 'Israel', 4);
INSERT INTO HR.COUNTRIES (COUNTRY_ID, COUNTRY_NAME, REGION_ID) VALUES ('IN', 'India', 3);
INSERT INTO HR.COUNTRIES (COUNTRY_ID, COUNTRY_NAME, REGION_ID) VALUES ('IT', 'Italy', 1);
INSERT INTO HR.COUNTRIES (COUNTRY_ID, COUNTRY_NAME, REGION_ID) VALUES ('JP', 'Japan', 3);
INSERT INTO HR.COUNTRIES (COUNTRY_ID, COUNTRY_NAME, REGION_ID) VALUES ('KW', 'Kuwait', 4);
INSERT INTO HR.COUNTRIES (COUNTRY_ID, COUNTRY_NAME, REGION_ID) VALUES ('ML', 'Malaysia', 3);
INSERT INTO HR.COUNTRIES (COUNTRY_ID, COUNTRY_NAME, REGION_ID) VALUES ('MX', 'Mexico', 2);
INSERT INTO HR.COUNTRIES (COUNTRY_ID, COUNTRY_NAME, REGION_ID) VALUES ('NG', 'Nigeria', 4);
INSERT INTO HR.COUNTRIES (COUNTRY_ID, COUNTRY_NAME, REGION_ID) VALUES ('NL', 'Netherlands', 1);
INSERT INTO HR.COUNTRIES (COUNTRY_ID, COUNTRY_NAME, REGION_ID) VALUES ('SG', 'Singapore', 3);
INSERT INTO HR.COUNTRIES (COUNTRY_ID, COUNTRY_NAME, REGION_ID) VALUES ('UK', 'United Kingdom', 1);
INSERT INTO HR.COUNTRIES (COUNTRY_ID, COUNTRY_NAME, REGION_ID) VALUES ('US', 'United States of America', 2);
INSERT INTO HR.COUNTRIES (COUNTRY_ID, COUNTRY_NAME, REGION_ID) VALUES ('ZM', 'Zambia', 4);
INSERT INTO HR.COUNTRIES (COUNTRY_ID, COUNTRY_NAME, REGION_ID) VALUES ('ZW', 'Zimbabwe', 4);