create table DEPARTMENTS
(
    DEPARTMENT_ID   NUMBER(4)    not null
        constraint DEPT_ID_PK
            primary key,
    DEPARTMENT_NAME VARCHAR2(30) not null
        constraint DEPT_NAME_NN
            check ("DEPARTMENT_NAME" IS NOT NULL),
    MANAGER_ID      NUMBER(6)
        constraint DEPT_MGR_FK
            references EMPLOYEES,
    LOCATION_ID     NUMBER(4)
        constraint DEPT_LOC_FK
            references LOCATIONS
)
/

comment on table DEPARTMENTS is 'Departments table that shows details of departments where employees
work. Contains 27 rows; references with locations, employees, and job_history tables.'
/

comment on column DEPARTMENTS.DEPARTMENT_ID is 'Primary key column of departments table.'
/

comment on column DEPARTMENTS.DEPARTMENT_NAME is 'A not null column that shows name of a department. Administration,
Marketing, Purchasing, Human Resources, Shipping, IT, Executive, Public
Relations, Sales, Finance, and Accounting. '
/

comment on column DEPARTMENTS.MANAGER_ID is 'Manager_id of a department. Foreign key to employee_id column of employees table. The manager_id column of the employee table references this column.'
/

comment on column DEPARTMENTS.LOCATION_ID is 'Location id where a department is located. Foreign key to location_id column of locations table.'
/

create index DEPT_LOCATION_IX
    on DEPARTMENTS (LOCATION_ID)
/

INSERT INTO HR.DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID) VALUES (10, 'Administration', 200, 1700);
INSERT INTO HR.DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID) VALUES (20, 'Marketing', 201, 1800);
INSERT INTO HR.DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID) VALUES (30, 'Purchasing', 114, 1700);
INSERT INTO HR.DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID) VALUES (40, 'Human Resources', 203, 2400);
INSERT INTO HR.DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID) VALUES (50, 'Shipping', 121, 1500);
INSERT INTO HR.DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID) VALUES (60, 'IT', 103, 1400);
INSERT INTO HR.DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID) VALUES (70, 'Public Relations', 204, 2700);
INSERT INTO HR.DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID) VALUES (80, 'Sales', 145, 2500);
INSERT INTO HR.DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID) VALUES (90, 'Executive', 100, 1700);
INSERT INTO HR.DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID) VALUES (100, 'Finance', 108, 1700);
INSERT INTO HR.DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID) VALUES (110, 'Accounting', 205, 1700);
INSERT INTO HR.DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID) VALUES (120, 'Treasury', null, 1700);
INSERT INTO HR.DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID) VALUES (130, 'Corporate Tax', null, 1700);
INSERT INTO HR.DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID) VALUES (140, 'Control And Credit', null, 1700);
INSERT INTO HR.DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID) VALUES (150, 'Shareholder Services', null, 1700);
INSERT INTO HR.DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID) VALUES (160, 'Benefits', null, 1700);
INSERT INTO HR.DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID) VALUES (170, 'Manufacturing', null, 1700);
INSERT INTO HR.DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID) VALUES (180, 'Construction', null, 1700);
INSERT INTO HR.DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID) VALUES (190, 'Contracting', null, 1700);
INSERT INTO HR.DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID) VALUES (200, 'Operations', null, 1700);
INSERT INTO HR.DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID) VALUES (210, 'IT Support', null, 1700);
INSERT INTO HR.DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID) VALUES (220, 'NOC', null, 1700);
INSERT INTO HR.DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID) VALUES (230, 'IT Helpdesk', null, 1700);
INSERT INTO HR.DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID) VALUES (240, 'Government Sales', null, 1700);
INSERT INTO HR.DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID) VALUES (250, 'Retail Sales', null, 1700);
INSERT INTO HR.DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID) VALUES (260, 'Recruiting', null, 1700);
INSERT INTO HR.DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID) VALUES (270, 'Payroll', null, 1700);