create table HAKJUM
(
    GRADE     CHAR(3),
    MIN_POINT NUMBER,
    MAX_POINT NUMBER
)
/

INSERT INTO HR.HAKJUM (GRADE, MIN_POINT, MAX_POINT) VALUES ('A+ ', 96, 100);
INSERT INTO HR.HAKJUM (GRADE, MIN_POINT, MAX_POINT) VALUES ('A0 ', 90, 95);
INSERT INTO HR.HAKJUM (GRADE, MIN_POINT, MAX_POINT) VALUES ('B+ ', 86, 89);
INSERT INTO HR.HAKJUM (GRADE, MIN_POINT, MAX_POINT) VALUES ('B0 ', 80, 85);
INSERT INTO HR.HAKJUM (GRADE, MIN_POINT, MAX_POINT) VALUES ('C+ ', 76, 79);
INSERT INTO HR.HAKJUM (GRADE, MIN_POINT, MAX_POINT) VALUES ('C0 ', 70, 75);
INSERT INTO HR.HAKJUM (GRADE, MIN_POINT, MAX_POINT) VALUES ('D  ', 0, 69);