create table TEST_NOVALIDATE
(
    NO   NUMBER       not null
        primary key,
    NAME VARCHAR2(10) not null
)
/

INSERT INTO HR.TEST_NOVALIDATE (NO, NAME) VALUES (1, 'AAA');
INSERT INTO HR.TEST_NOVALIDATE (NO, NAME) VALUES (2, 'BBB');
INSERT INTO HR.TEST_NOVALIDATE (NO, NAME) VALUES (3, 'CCC');