create table TEST
(
    NAME VARCHAR2(10),
    AGE  NUMBER(3)
)
/

INSERT INTO HR.TEST (NAME, AGE) VALUES (null, 33);
INSERT INTO HR.TEST (NAME, AGE) VALUES ('bb', 22);
INSERT INTO HR.TEST (NAME, AGE) VALUES ('bb', 22);